name: Cypress Computers

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          build: npx cypress run --record --key dfac4085-6709-4abb-90cd-6c41b9dcaae6 -- spec 'cypress\integration\*.js'
          # start: npm start
